name: Main
on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - elixir-version: "> 0"
            otp-version: "28.0.1"

          - elixir-version: "1.18.4"
            otp-version: "> 0"

          - elixir-version: "1.18.4"
            otp-version: master

          - elixir-version: main
            otp-version: master

          - elixir-version: main-otp-28
            otp-version: master

          - elixir-version: "1.x.y"
            otp-version: master

          - elixir-version: "> 0"
            otp-version: master

          - elixir-version: "> 0-otp-28"
            otp-version: master

    steps:
      - uses: erlef/setup-beam@fix/calculating-otp-major-for-elixir
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - run: |
          echo Elixir:
          elixir --version
          echo OTP:
          elixir -e 'IO.write File.read!("#{:code.root_dir()}/releases/#{System.otp_release()}/OTP_VERSION")'

