name: Main
on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - elixir-version: "1.18.4"
            otp-version: "26"
            version-type: 'strict'

    steps:
      - uses: erlef/setup-beam@fix/more-versioning
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - run: |
          echo Elixir:
          elixir --version
          echo OTP:
          elixir -e 'IO.write File.read!("#{:code.root_dir()}/releases/#{System.otp_release()}/OTP_VERSION")'

