name: Main
on:
  push:
jobs:
  elixir-latest:
    runs-on: ubuntu-24.04
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "> 0"
          otp-version: "28.0.1"
      - run: |
          elixir --version

  otp-latest:
    runs-on: ubuntu-24.04
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.4"
          otp-version: "> 0"
      - run: |
          elixir --version
